#!/usr/bin/env python
"""Generate the API parameter tables in ``docs/`` from the code they describe.

The parameter tables for ``optimize()`` and ``ObjectiveConfig`` are long,
they appear in three documents, and each row restates something the
signature and the docstring already say.  Restating is how they drifted: a
docs audit found ``optimize()`` documented with a ``pruner`` parameter it
does not accept and without five it does, in two files at once, plus an
``ObjectiveConfig`` table missing six fields.  None of that is a mistake a
reader could catch, because nothing in the document disagrees with itself.

So the tables are no longer written.  They are rendered from
``inspect.signature`` and the numpydoc ``Parameters`` block into regions
delimited by::

    <!-- BEGIN GENERATED: <region> -->
    <!-- END GENERATED: <region> -->

Everything outside a region is hand-written and never touched, which is the
point: the prose that explains *why* a parameter exists stays prose, and
only the enumerable part -- name, default, one-line description -- is
mechanical.

This shifts the failure mode rather than removing it.  A row can still be
wrong, but only by way of a wrong docstring, where the wrongness sits next
to the code and is visible to anyone changing it.  What it can no longer be
is *absent* or *invented*: the row set is the parameter set.

To change a table, edit the docstring.  Then run this script.

Usage
-----
``python scripts/gen_param_tables.py``           rewrite the regions
``python scripts/gen_param_tables.py --check``   fail if they are stale

``--check`` exits non-zero with a unified diff, and runs in CI via
``pytest tests/test_param_tables.py``.

Unlike ``scripts/check_citations.py``, this imports ``bayesflow_hpo``, so it
needs the package installed and ``KERAS_BACKEND`` set.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import inspect
import os
import re
import sys
import textwrap
from collections.abc import Callable
from dataclasses import MISSING, fields, is_dataclass
from pathlib import Path
from typing import Any, NamedTuple

__all__ = [
    "Param",
    "collect_params",
    "main",
    "render_dataclass_block",
    "render_signature_block",
    "render_table",
    "splice",
]

#: Set before importing the package.  Importing ``bayesflow`` without a
#: backend raises, and this script is run from CI and from a bare shell as
#: often as from a configured one.
os.environ.setdefault("KERAS_BACKEND", "torch")

_BEGIN = "<!-- BEGIN GENERATED: {} -->"
_END = "<!-- END GENERATED: {} -->"

#: Written into every region so that someone editing a table in place is
#: told where the text actually comes from before they waste the edit.
_NOTE = (
    "<!-- Generated by scripts/gen_param_tables.py from the docstring. "
    "Edit the docstring, not this block. -->"
)

#: numpydoc section headings that end the ``Parameters`` block.
_SECTIONS = frozenset({
    "Returns", "Yields", "Raises", "Warns", "Other Parameters",
    "Attributes", "Methods", "See Also", "Notes", "References", "Examples",
})


class Param(NamedTuple):
    """One parameter, as the documents need it."""

    name: str
    #: Default as written in the source (``MAX_PARAM_COUNT``), for the
    #: signature block, or ``None`` when the parameter is required.
    literal: str | None
    #: Default evaluated (``1000000``), for the tables.  A reader comparing
    #: a table against a run wants the value, not the constant's name.
    value: str | None
    description: str
    keyword_only: bool


def _clean(doc: str | None) -> list[str]:
    return inspect.cleandoc(doc or "").split("\n")


def _rst_to_markdown(text: str) -> str:
    """Convert the RST a numpydoc description uses into Markdown."""
    # :class:`~pkg.mod.Name` / :func:`pkg.f` -> `Name` / `f`
    text = re.sub(
        r":[a-z:]+:`~?([^`<]+?)(?:\s*<[^`>]+>)?`",
        lambda m: f"`{m.group(1).rsplit('.', 1)[-1]}`",
        text,
    )
    text = text.replace("``", "`")
    # A literal pipe would end the table cell.
    return text.replace("|", r"\|")


def _first_paragraph(body: list[str]) -> str:
    """The lead paragraph of a numpydoc entry, as one line.

    Later paragraphs are caveats and worked examples -- the ``validate_fn``
    entry runs to four of them -- which belong in the prose sections, not in
    a table cell.
    """
    para: list[str] = []
    for line in body:
        if not line.strip():
            if para:
                break
            continue
        para.append(line.strip())
    # Sentence-separating double spaces survive the join and read as a gap
    # in a table cell.
    return re.sub(r"\s+", " ", _rst_to_markdown(" ".join(para)))


def _parse_docstring(doc: str | None) -> dict[str, str]:
    """Map parameter name -> lead-paragraph description.

    numpydoc allows one entry to name several parameters
    (``simulator, adapter``); each gets the shared description.
    """
    lines = _clean(doc)
    try:
        start = lines.index("Parameters")
    except ValueError:
        return {}
    if start + 1 >= len(lines) or not set(lines[start + 1].strip()) <= {"-"}:
        return {}

    entries: dict[str, str] = {}
    names: list[str] = []
    body: list[str] = []

    def flush() -> None:
        if names:
            text = _first_paragraph(body)
            for name in names:
                entries[name] = text

    for line in lines[start + 2:]:
        stripped = line.strip()
        is_heading = bool(stripped) and not line[0].isspace()
        if is_heading and stripped in _SECTIONS:
            break
        if is_heading:
            flush()
            # "name : type" and "a, b" are both legal headings.
            names = [n.strip() for n in stripped.split(":")[0].split(",")]
            names = [n for n in names if n]
            body = []
        else:
            body.append(line)
    flush()
    return entries


def _source_defaults(obj: Callable[..., Any] | type) -> dict[str, str]:
    """Default expressions as written, via the AST.

    ``inspect.signature`` evaluates them, so ``max_param_count`` comes back
    as ``1000000`` and the signature block loses the name that says where
    the number is defined.
    """
    try:
        tree = ast.parse(textwrap.dedent(inspect.getsource(obj)))
    except (OSError, TypeError, SyntaxError):  # pragma: no cover
        return {}
    node = tree.body[0]
    out: dict[str, str] = {}

    if isinstance(node, ast.ClassDef):
        for stmt in node.body:
            if isinstance(stmt, ast.AnnAssign) and stmt.value is not None:
                if isinstance(stmt.target, ast.Name):
                    out[stmt.target.id] = ast.unparse(stmt.value)
        return out

    if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        return {}
    args = node.args
    positional = args.posonlyargs + args.args
    for arg, default in zip(positional[len(positional) - len(args.defaults):],
                            args.defaults):
        out[arg.arg] = ast.unparse(default)
    for arg, default in zip(args.kwonlyargs, args.kw_defaults):
        if default is not None:
            out[arg.arg] = ast.unparse(default)
    return out


def _render_value(value: Any) -> str:
    """Evaluated default, as a table shows it."""
    return repr(value)


def collect_params(obj: Callable[..., Any] | type) -> list[Param]:
    """Introspect *obj* into the rows its tables need.

    Raises
    ------
    ValueError
        If a parameter has no docstring entry.  A table that silently
        rendered an empty cell would reproduce, in a new mechanism, exactly
        the gap this script exists to close.
    """
    described = _parse_docstring(obj.__doc__)
    literals = _source_defaults(obj)
    params: list[Param] = []

    if is_dataclass(obj):
        for f in fields(obj):
            if f.default is not MISSING:
                value: str | None = _render_value(f.default)
            elif f.default_factory is not MISSING:  # type: ignore[misc]
                value = _render_value(f.default_factory())
            else:
                value = None
            params.append(Param(
                name=f.name,
                literal=literals.get(f.name),
                value=value,
                description=described.get(f.name, ""),
                # Only the signature renderer reads this, and it renders
                # functions.
                keyword_only=False,
            ))
    else:
        for name, p in inspect.signature(obj).parameters.items():
            if p.kind in (p.VAR_POSITIONAL, p.VAR_KEYWORD):
                continue
            params.append(Param(
                name=name,
                literal=literals.get(name),
                value=(None if p.default is p.empty
                       else _render_value(p.default)),
                description=described.get(name, ""),
                keyword_only=p.kind is p.KEYWORD_ONLY,
            ))

    undocumented = [p.name for p in params if not p.description]
    if undocumented:
        raise ValueError(
            f"{obj.__name__} has no docstring entry for: "
            f"{', '.join(undocumented)}. Add one to the Parameters block "
            f"-- the generated table has no other source for the text."
        )
    return params


#: A trailing "(default 50)" restating the Default column beside it.
_TRAILING_DEFAULT = re.compile(r"\s*\((?:the\s+)?default[^()]*\)\s*(?=\.?$)", re.I)


def render_table(params: list[Param], *, header: str, defaults: bool) -> str:
    """Render rows as a Markdown table."""
    if defaults:
        out = [f"| {header} | Default | Description |",
               "|---|---|---|"]
        for p in params:
            default = "*(required)*" if p.value is None else f"`{p.value}`"
            # The column already says it; saying it twice per row is noise.
            text = _TRAILING_DEFAULT.sub("", p.description).strip()
            out.append(f"| `{p.name}` | {default} | {text} |")
    else:
        out = [f"| {header} | Description |", "|---|---|"]
        for p in params:
            out.append(f"| `{p.name}` | {p.description} |")
    return "\n".join(out)


def render_signature_block(obj: Callable[..., Any], name: str) -> str:
    """Render ``def name(...) -> R`` as a wrapped code fence."""
    sig = inspect.signature(obj)
    parts: list[str] = []
    star_emitted = False
    for pname, p in sig.parameters.items():
        if p.kind is p.VAR_KEYWORD:
            parts.append(f"**{pname}")
            continue
        if p.kind is p.VAR_POSITIONAL:
            parts.append(f"*{pname}")
            star_emitted = True
            continue
        if p.kind is p.KEYWORD_ONLY and not star_emitted:
            parts.append("*")
            star_emitted = True
        literal = _source_defaults(obj).get(pname)
        parts.append(pname if p.default is p.empty else f"{pname}={literal}")

    returns = ""
    if sig.return_annotation is not sig.empty:
        annotation = sig.return_annotation
        text = annotation if isinstance(annotation, str) else (
            getattr(annotation, "__name__", str(annotation))
        )
        returns = f" -> {text}"

    body = textwrap.wrap(
        ", ".join(parts), width=72,
        initial_indent="    ", subsequent_indent="    ",
        break_long_words=False, break_on_hyphens=False,
    )
    return "\n".join(
        ["```python", f"def {name}("] + body + [f"){returns}", "```"]
    )


def render_dataclass_block(obj: type, name: str) -> str:
    """Render the dataclass field list as a code fence."""
    literals = _source_defaults(obj)
    lines = ["```python", "@dataclass", f"class {name}:"]
    for f in fields(obj):
        annotation = f.type if isinstance(f.type, str) else str(f.type)
        literal = literals.get(f.name)
        suffix = f" = {literal}" if literal is not None else ""
        lines.append(f"    {f.name}: {annotation}{suffix}")
    lines.append("```")
    return "\n".join(lines)


def splice(text: str, region: str, body: str) -> str:
    """Replace one delimited region's contents, keeping the markers.

    Raises
    ------
    ValueError
        If the region's markers are missing or not a matched pair.  A
        silently skipped region is a table that stops being regenerated
        without anything saying so.
    """
    begin, end = _BEGIN.format(region), _END.format(region)
    if text.count(begin) != 1 or text.count(end) != 1:
        raise ValueError(f"expected exactly one {begin} ... {end} pair")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{begin}\n{_NOTE}\n\n{body}\n{end}{tail}"


def build_regions() -> dict[str, dict[str, str]]:
    """Map document path -> region name -> rendered body."""
    import bayesflow_hpo
    from bayesflow_hpo.optimization.objective import ObjectiveConfig

    optimize_params = collect_params(bayesflow_hpo.optimize)
    config_params = collect_params(ObjectiveConfig)

    return {
        "docs/api_reference.md": {
            "optimize-signature": render_signature_block(
                bayesflow_hpo.optimize, "optimize"
            ),
            "optimize-params": render_table(
                optimize_params, header="Parameter", defaults=False
            ),
            "objectiveconfig-params": render_table(
                config_params, header="Field", defaults=True
            ),
        },
        "docs/defaults.md": {
            "optimize-defaults": render_table(
                optimize_params, header="Parameter", defaults=True
            ),
        },
        "docs/optimization.md": {
            "objectiveconfig-dataclass": render_dataclass_block(
                ObjectiveConfig, "ObjectiveConfig"
            ),
        },
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="exit non-zero if any region is stale, without writing",
    )
    parser.add_argument("--root", default=".", type=Path)
    args = parser.parse_args(argv)

    stale: list[str] = []
    for relative, regions in build_regions().items():
        path = args.root / relative
        original = path.read_text(encoding="utf-8")
        updated = original
        for region, body in regions.items():
            updated = splice(updated, region, body)
        if updated == original:
            continue
        if args.check:
            stale.append(relative)
            sys.stdout.writelines(difflib.unified_diff(
                original.splitlines(keepends=True),
                updated.splitlines(keepends=True),
                fromfile=f"{relative} (committed)",
                tofile=f"{relative} (generated)",
            ))
        else:
            path.write_text(updated, encoding="utf-8")
            print(f"updated {relative}")

    if stale:
        print(
            f"\n{len(stale)} file(s) out of date with the code they describe. "
            f"Run: python scripts/gen_param_tables.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("Generated parameter tables match the code.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
